version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123456

    volumes:
      - postgres:/data/postgres
      - postgresql:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

  http_rest_api:
    container_name: http_rest_api
    image: http_rest_api_image

    depends_on:
      - postgres

    restart: unless-stopped

    working_dir: /app
    expose:
      - 8080
    ports:
      - "8080:8080"


volumes:
  postgres:
  postgresql:
